export const LOGIN_USER_START = 'LOGIN_STUDENTS_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_STUDENTS_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_STUDENTS_FAIL';

export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL';